version: '3'
services:
    web-backend:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - $HOME/.aws/credentials:/home/app/.aws/credentials
    # web-frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile.front
        