version: '3'
services:
    web-backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - $HOME/.aws/credentials:/home/app/.aws/credentials
    web-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"