version: '3'
services:
    web:
        build: .
        #command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --app-dir ./backend/
        ports:
            - "8080:8000"
        volumes:
            - $HOME/.aws/credentials:/home/app/.aws/credentials
            - .:/app