version: '3'
services:
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - $HOME/.aws/credentials:/root/.aws/credentials
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "80:80"