# Pull the base image with python 3.8 as a runtime for your Lambda
FROM python:3.8-slim-buster

# Copy the earlier created requirements.txt file to the container
COPY requirements.txt ./

# Install the python requirements from requirements.txt
RUN python3.8 -m pip install -r requirements.txt

# Copy function codes and folders to container
COPY *.pt ./
COPY *.py ./
RUN ["python","setup.py"]

# Set the CMD to your handler
CMD ["python","app.py"]