name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-docker: # Deploy Image to Docker registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with: 
          name: reoneo/buildon-backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./backend/
          
