name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-docker: # Deploy Image to Docker registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish backend image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with: 
          name: reoneo/buildon-backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./backend/
      - name: Publish frontend image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with: 
          name: reoneo/buildon-frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./frontend/
  deploy-eb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: buildon-app
          environment_name: Buildonapp-env
          version_label: 1
          region: ap-southeast-1